package alancasas.Concesionaria.igu;

import alancasas.Concesionaria.logica.ControladoraLogica;
import java.awt.Color;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class AltaVehiculo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AltaVehiculo.class.getName());

    private ControladoraLogica controlLogic;

    public AltaVehiculo() {
        initComponents();
        controlLogic = new ControladoraLogica();
        this.setResizable(false); //Hace que no sea reescalable (evita romper le diseño)
        this.setFocusable(true); //Evita que ponga directamente el focus del teclado(el usuario debe hacer click en los campos)
        this.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_titulo = new javax.swing.JLabel();
        label_icon = new javax.swing.JLabel();
        panel_form = new javax.swing.JPanel();
        label_modelo = new javax.swing.JLabel();
        label_marca = new javax.swing.JLabel();
        label_patente = new javax.swing.JLabel();
        label_color = new javax.swing.JLabel();
        label_cant_puertas = new javax.swing.JLabel();
        txt_modelo = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_patente = new javax.swing.JTextField();
        combo_color = new javax.swing.JComboBox<>();
        combo_puertas = new javax.swing.JComboBox<>();
        panel_btns = new javax.swing.JPanel();
        btn_volver = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_titulo.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        label_titulo.setText("Alta Vehiculos");

        label_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/toyota3.png"))); // NOI18N
        label_icon.setText("jLabel2");

        label_modelo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_modelo.setText("Modelo: ");

        label_marca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_marca.setText("Marca: ");

        label_patente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_patente.setText("Patente: ");

        label_color.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_color.setText("Color: ");

        label_cant_puertas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label_cant_puertas.setText("Cant.Puertas: ");

        txt_modelo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txt_modelo.setText("Ingrese el modelo");
        txt_modelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_modeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_modeloFocusLost(evt);
            }
        });

        txt_marca.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txt_marca.setText("Ingrese la marca");
        txt_marca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_marcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_marcaFocusLost(evt);
            }
        });

        txt_patente.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        txt_patente.setText("Ingrese la patente");
        txt_patente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_patenteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_patenteFocusLost(evt);
            }
        });

        combo_color.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        combo_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Amarillo", "Azul", "Blanco", "Gris", "Negro", "Rojo", "Verde", "Violeta" }));

        combo_puertas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        combo_puertas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "2", "3", "4", "5" }));

        javax.swing.GroupLayout panel_formLayout = new javax.swing.GroupLayout(panel_form);
        panel_form.setLayout(panel_formLayout);
        panel_formLayout.setHorizontalGroup(
            panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_formLayout.createSequentialGroup()
                        .addComponent(label_patente)
                        .addGap(18, 18, 18)
                        .addComponent(txt_patente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_formLayout.createSequentialGroup()
                        .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_modelo)
                            .addComponent(label_marca))
                        .addGap(18, 18, 18)
                        .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_formLayout.createSequentialGroup()
                        .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_cant_puertas)
                            .addComponent(label_color))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_color, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panel_formLayout.setVerticalGroup(
            panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_modelo)
                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_marca)
                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_patente)
                    .addComponent(txt_patente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_color)
                    .addComponent(combo_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_cant_puertas)
                    .addComponent(combo_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btn_volver.setText("Volver");
        btn_volver.addActionListener(this::btn_volverActionPerformed);

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(this::btn_limpiarActionPerformed);

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(this::btn_guardarActionPerformed);

        javax.swing.GroupLayout panel_btnsLayout = new javax.swing.GroupLayout(panel_btns);
        panel_btns.setLayout(panel_btnsLayout);
        panel_btnsLayout.setHorizontalGroup(
            panel_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_btnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_btnsLayout.setVerticalGroup(
            panel_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_btnsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_btnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(label_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panel_btns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panel_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(panel_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(label_icon)))
                .addGap(18, 18, 18)
                .addComponent(panel_btns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        Home principal = new Home(); //Creo instancia de la ventana principal                
        principal.setVisible(true); //Hago la ventana principal visible
        principal.setLocationRelativeTo(null); //Que aparezca en el medio
        this.dispose();//Cierro la ventana actual y libero recursos
    }//GEN-LAST:event_btn_volverActionPerformed

    private void txt_modeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_modeloFocusGained
        if (String.valueOf(txt_modelo.getText()).equals("Ingrese el modelo")) {
            txt_modelo.setText(""); //Si dejas un espacio sigue siendo un caracter
            txt_modelo.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_modeloFocusGained

    private void txt_modeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_modeloFocusLost
        if ((txt_modelo.getText()).isBlank()) {
            txt_modelo.setText("Ingrese el modelo");
            txt_modelo.setForeground(new Color(255, 0, 0));
        }
    }//GEN-LAST:event_txt_modeloFocusLost

    private void txt_marcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_marcaFocusGained
        if (String.valueOf(txt_marca.getText()).equals("Ingrese la marca")) {
            txt_marca.setText("");
            txt_marca.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_marcaFocusGained

    private void txt_marcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_marcaFocusLost
        if (txt_marca.getText().isBlank()) {
            txt_marca.setText("Ingrese la marca");
            txt_marca.setForeground(new Color(255, 0, 0));
        }
    }//GEN-LAST:event_txt_marcaFocusLost

    private void txt_patenteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patenteFocusGained
        if (String.valueOf(txt_patente.getText()).equals("Ingrese la patente")) {
            txt_patente.setText("");
            txt_patente.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_patenteFocusGained

    private void txt_patenteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_patenteFocusLost
        if (txt_patente.getText().isBlank()) {
            txt_patente.setText("Ingrese la patente");
            txt_patente.setForeground(new Color(255, 0, 0));
        }
    }//GEN-LAST:event_txt_patenteFocusLost

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txt_modelo.setText("Ingrese el modelo");
        txt_marca.setText("Ingrese la marca");
        txt_patente.setText("Ingrese la patente");
        combo_color.setSelectedIndex(0);
        combo_puertas.setSelectedIndex(0);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed

        if (validarFormulario()) {
            if (!confirmarAccion("¿Desea guardar el nuevo registro?", "Confirmación")) {
                return;
            }

            String modelo = txt_modelo.getText();
            String marca = txt_marca.getText();
            String patente = txt_patente.getText().toUpperCase(); //Las patentes siempre en mayusculas
            String color = (String) combo_color.getSelectedItem();
            String cantPuertas = (String) combo_puertas.getSelectedItem();

            if(controlLogic.guardarVehiculo(modelo, marca, patente, color, cantPuertas)){
                mostrarMensaje("Se guardo correctamente", "info", "Titulo");
                btn_limpiarActionPerformed(evt); //borra le formulario luego del guardado
                btn_volverActionPerformed(evt); //regresa a la tabla de mostrar
            } else {
                mostrarMensaje("ERROR: No se pudo guardar el vehiculo", "error", "Titulo");            
            }           

        } else {
            mostrarMensaje("Error: Se debe completar todos los campos para dar el alta", "error", "Campos incompletos");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AltaVehiculo().setVisible(true));
    }

    private boolean validarFormulario() {
        /*TODO metodo para llamar en guardar*/
        if (txt_modelo.getText().equals("Ingrese el modelo") || txt_modelo.getText().isBlank()) {
            return false;
        } else if (txt_marca.getText().equals("Ingrese la marca") || txt_marca.getText().isBlank()) {
            return false;
        } else if (txt_patente.getText().equals("Ingrese la patente") || txt_patente.getText().isBlank()) {
            return false;
        } else if (combo_color.getSelectedItem().equals("-")) {
            return false;
        } else if (combo_puertas.getSelectedItem().equals("-")) {
            return false;
        } else {
            return true;
        }
    }

    private void mostrarMensaje(String mensaje, String tipo, String titulo) {
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("info")) {
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        } else if (tipo.equals("error")) {
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }

        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }

    /*AVISO DE CONFIRMACION (usando en boton guardar -modificar-)*/
    private boolean confirmarAccion(String mensaje, String titulo) {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                mensaje,
                titulo,
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );
        return opcion == JOptionPane.YES_OPTION;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> combo_color;
    private javax.swing.JComboBox<String> combo_puertas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_cant_puertas;
    private javax.swing.JLabel label_color;
    private javax.swing.JLabel label_icon;
    private javax.swing.JLabel label_marca;
    private javax.swing.JLabel label_modelo;
    private javax.swing.JLabel label_patente;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JPanel panel_btns;
    private javax.swing.JPanel panel_form;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_patente;
    // End of variables declaration//GEN-END:variables
}
